# Security Groups:
# Se abren puertos 3000 (backend) y 5000 (frontend) para permitir acceso a la aplicación desde navegador.
# En produccion no se recomienda 0.0.0.0/0.

AWSTemplateFormatVersion: "2010-09-09"
Description: Infraestructura Mi Energia DevOps

Resources:

  MiBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mi-energia-devops-bucket

  MiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acceso a la aplicacion
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  MiEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      SecurityGroups:
        - !Ref MiSecurityGroup